// GENERATED by Tools/generate_melodia_rules.py from Plugins/MelodiaCore/Rules/melodia_rules.json
// DO NOT EDIT ΓÇö edit the JSON and regenerate. Rules version 3.
#pragma once

#include "HAL/Platform.h"
#include "UObject/NameTypes.h"

namespace MelodiaRulesGen
{
	// Rhythm
	constexpr float PerfectWindowMs = 90.0f;
	constexpr float GreatWindowMs = 120.0f;
	constexpr float GoodWindowMs = 160.0f;
	constexpr float PerfectMultiplier = 1.5f;
	constexpr float GreatMultiplier = 1.25f;
	constexpr float GoodMultiplier = 1.0f;
	constexpr float MissMultiplier = 0.55f;
	constexpr float MaxCombatMultiplier = 1.5f;
	constexpr float ComboBonusPerHit = 0.05f;
	// Turn economy
	constexpr int32 BaseAV = 10000;
	constexpr int32 SharedSPStart = 3;
	constexpr int32 SharedSPMax = 5;
	// Songcraft
	constexpr int32 CrescendoMax = 100;
	constexpr int32 CrescendoGainPerfect = 12;
	constexpr int32 CrescendoGainGreat = 8;
	constexpr int32 CrescendoGainGood = 5;
	constexpr int32 CrescendoGainMiss = 0;
	// Ultimate
	constexpr float UltGainPerHit = 5.0f;
	constexpr float UltGainPerfect = 10.0f;
	constexpr float UltMax = 100.0f;
	constexpr float UltDamageMult = 3.0f;
	// Toughness
	constexpr float ToughnessReduction = 0.4f;
	constexpr float ToughnessBrokenEnemyDamageMult = 0.5f;
	// Authored opening flow
	constexpr const TCHAR* OpeningMorningLevel = TEXT("/Game/Melodia/Levels/Opening/L_MelusinaMorning");
	constexpr const TCHAR* OpeningDreamstateLevel = TEXT("/Game/Melodia/Levels/Opening/L_Melodia_Dreamstate");
	constexpr const TCHAR* OpeningZenLevel = TEXT("/Game/ZenForestTest");
	constexpr const TCHAR* OpeningTutorialEnemyId = TEXT("SakuraPhantom");
	constexpr int32 OpeningFirstDungeonSeed = 1337;
	constexpr int32 OpeningHeartTokensOnUnlock = 1;

	struct FGeneratedSkillEffect
	{
		const TCHAR* SkillId;
		float ToughnessScalar;
		float BonusDamageOnBreak;
		float EnemyDelayOnBreakAvFraction;
		float EnemyDelayOnHitAvFraction;
		float HealOnHitScalar;
		float UltGainBonusOnPerfect;
		int32 SpGainOnPerfect;
		const TCHAR* ModifierOnHit;
		const TCHAR* ModifierOnPerfect;
	};

	inline const FGeneratedSkillEffect* GetSkillEffectTable(int32& OutCount)
	{
		static const FGeneratedSkillEffect Table[] =
		{
		{ TEXT("StarlitPing"), 0.8f, 0.0f, 0.0f, 0.0f, 0.0f, 3.0f, 1, nullptr, TEXT("Crescendo_Minor") },
		{ TEXT("TidalWave"), 1.8f, 8.0f, 0.35f, 0.0f, 0.0f, 0.0f, 0, nullptr, nullptr },
		{ TEXT("GustStaccato"), 0.9f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0, TEXT("HasteDance"), nullptr },
		{ TEXT("MoonStep"), 1.0f, 0.0f, 0.0f, 0.2f, 0.0f, 0.0f, 0, nullptr, nullptr },
		{ TEXT("StoneWall"), 1.2f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0, TEXT("GuardHymn"), nullptr },
		{ TEXT("TidalMend"), 0.4f, 0.0f, 0.0f, 0.0f, 0.18f, 0.0f, 0, nullptr, TEXT("GuardHymn") }
		};
		OutCount = UE_ARRAY_COUNT(Table);
		return Table;
	}

	inline FName NormalizeSongcraftSkillId(FName SkillId)
	{
		static const struct { const TCHAR* From; const TCHAR* To; } Aliases[] =
		{
		{ TEXT("Skill_Lv01_StarlitPing"), TEXT("StarlitPing") },
		{ TEXT("StarlitPing"), TEXT("StarlitPing") },
		{ TEXT("Skill_Lv02_MoonStep"), TEXT("MoonStep") },
		{ TEXT("MoonStep"), TEXT("MoonStep") },
		{ TEXT("Skill_Lv05_GoldStuccoStrike"), TEXT("TidalWave") },
		{ TEXT("TidalWave"), TEXT("TidalWave") },
		{ TEXT("Skill_Lv06_EscherClimb"), TEXT("GustStaccato") },
		{ TEXT("GustStaccato"), TEXT("GustStaccato") },
		{ TEXT("Skill_Lv12_CathedralChant"), TEXT("StoneWall") },
		{ TEXT("StoneWall"), TEXT("StoneWall") },
		{ TEXT("Skill_Lv03_CherryArpeggio"), TEXT("TidalMend") },
		{ TEXT("TidalMend"), TEXT("TidalMend") }
		};
		for (const auto& A : Aliases)
		{
			if (SkillId == FName(A.From))
			{
				return FName(A.To);
			}
		}
		return SkillId;
	}

	inline bool FindSkillEffect(FName SkillId, FGeneratedSkillEffect& OutEffect)
	{
		const FName Canonical = NormalizeSongcraftSkillId(SkillId);
		int32 Count = 0;
		const FGeneratedSkillEffect* Table = GetSkillEffectTable(Count);
		for (int32 i = 0; i < Count; ++i)
		{
			if (Canonical == FName(Table[i].SkillId))
			{
				OutEffect = Table[i];
				return true;
			}
		}
		return false;
	}


	struct FGeneratedModifier
	{
		const TCHAR* Id;
		const TCHAR* Stat;
		const TCHAR* Op;
		float Value;
		int32 DurationTurns;
		const TCHAR* Stacking;
		int32 MaxStacks;
	};

	inline const FGeneratedModifier* GetModifierTable(int32& OutCount)
	{
		static const FGeneratedModifier Table[] =
		{
		{ TEXT("Crescendo_Minor"), TEXT("attack"), TEXT("mul"), 1.1f, 2, TEXT("refresh"), 1 },
		{ TEXT("TempoBreak"), TEXT("speed"), TEXT("mul"), 0.85f, 2, TEXT("stack"), 3 },
		{ TEXT("GuardHymn"), TEXT("damage_taken"), TEXT("mul"), 0.8f, 1, TEXT("refresh"), 1 },
		{ TEXT("HasteDance"), TEXT("speed"), TEXT("mul"), 1.18f, 2, TEXT("refresh"), 1 },
		{ TEXT("ResonantFocus"), TEXT("ult_gain"), TEXT("mul"), 1.25f, 2, TEXT("refresh"), 1 }
		};
		OutCount = UE_ARRAY_COUNT(Table);
		return Table;
	}

	inline bool FindGeneratedModifier(FName ModifierId, FGeneratedModifier& OutMod)
	{
		int32 Count = 0;
		const FGeneratedModifier* Table = GetModifierTable(Count);
		for (int32 i = 0; i < Count; ++i)
		{
			if (ModifierId == FName(Table[i].Id))
			{
				OutMod = Table[i];
				return true;
			}
		}
		return false;
	}

}
